### ISSUE TITLE
Lineages.bed not matching the SNPs on the PathogenSeq download page

### ISSUE THREAD

**Issue by BertBog** [jodyphelan/TBProfiler#13]
Hi,

I am not completely sure if this is a bug or not, but some of the SNPs listed in the lineages.bed file do not match the ones listed in the Coll2014_LinSpeSNPs_final.csv file (from http://pathogenseq.lshtm.ac.uk/).

For example:
Lineages.bed
Chromosome	599868	599868	lineage4	**G	A**	Euro-American	LAM;T;S;X;H	None

CSV:
lineage4	599868	2670	**A/G**	890	CGA/CGG	R/R	Rv0507	mmpL2	syn	nonessential	yes

As you can see, in the lineages.bed the REF and the ALT columns are reversed. I noticed that it only happens in SNPs that are labelled as non-essential in the original CSV. For the other positions the order is the same in both files. 

Is there a reasons why they are reversed in those positions? As far as I understand, reversing would mean that those SNPs are never detected.

Best,
Bert

**Comment by jodyphelan** [comment]
Hi Bert,

In the CSV they are represented as REF/ALT. 

In the BED file the two columns have a slightly different. Specifically they are:
1) Allele **_not_ found** in lineage and 2) allele **found** in lineage
This mostly corresponds with the REF/ALT representation but because the H37Rv reference is a lineage 4 strain (and specifically lineage4.9), all the SNPs for those lineages are flipped around. Another way to think of it is that we are looking for the absence of an alternate allele for these positions.

Hope that helps,

Jody

**Comment by BertBog** [comment]
Alright, that explains it. Thanks a lot!
