### ISSUE TITLE
No lineage result

### ISSUE THREAD

**Issue by PaulineLempens** [jodyphelan/TBProfiler#130]
Hi Jody,

170/594 genomes that I ran through version 2.8.12 did not have a result for lineage. The majority did have a result earlier on when using version 2.8.6, and some had "root" as result at that time. There seems to be no lineage in particular that has no result with version 2.8.12.

What could be the cause of this?

Many thanks in advance.

**Comment by jodyphelan** [comment]
Hi Pauline,

Thanks for reporting that issue. I haven't seen that before. There could be a mismatch between the database and TBprofiler versions but that wouldn't explain why it did run correctly through for some samples. 

Could you run the following command and reply with the output?
```
cat $CONDA_PREFIX/share/tbprofiler/tbdb.version.json 
```

If we can't figure it out this way, would you be open to sharing an example file so that I could troubleshoot?

Jody
