### ISSUE TITLE
Variant Arg89Leu in Rv0678 missed in report?

### ISSUE THREAD

**Issue by wimmulders** [jodyphelan/TBProfiler#134]
Hi Jody,
I encountered a discordancy between the TBprofiler and Mtbseq pipelines. Arg89Leu in Rv0678 (mmpR5) didn't came out of the report of Tbprofiler (neither as dr variants or other variants). Looking at the BAM and VCF files the variant was clearly present. Could you help to clear this out?
Thanks a lot!
Best regards,
wim
![Screenshot 2020-12-09 at 11 35 54 (3)](https://user-images.githubusercontent.com/24397562/101632092-aae0eb00-3a25-11eb-9943-12682c2404b4.png)
[201502097.targets.vcf.gz](https://github.com/jodyphelan/TBProfiler/files/5665928/201502097.targets.vcf.gz)

**Comment by jodyphelan** [comment]
Hey Wim,

I had a look and I think I know what is going on. It seems there is a insertion before the SNP in question. Because the insertion  changes the frame it also affects and potentially changes the SNP. I noticed this is not reflected in the text or CSV report but is it present in the json report ("nucleotide_change": "779127T>TG+779255G>T"). That seems to be the first issue so I'll create a quick fix that.

Generally the approach of annotating multiple mutations together is the right thing to do, hoever if looks like your case if more complex.  I noticed that the allelic depth of these variant seem to suggest that these variants do not actually segregate together 
| Pos      | Ref (reads) | Alt (reads) |
| ----------- | ----------- |  ----------- |
| 779127      | T   (135)    | TG (22) |
| 779255   | G (30)        | T(135) |

I do not know anything about what you have sequenced or how the raw data looks like so I am making a lot of assumptions here. But if it is the case that you have sequenced a pool of bacteria with some containing one variant and the rest containing the other variant then it is important to not annotate them together. It then becomes important to phase the variants before annotating. This is not currently implemented in TB-Profiler but I could take a look if it is possible.

Jody
