### ISSUE TITLE
Add kraken2 filtering of reads

### ISSUE THREAD

**Issue by jodyphelan** [jodyphelan/TBProfiler#156]
### Summary
Kraken2 can be used to classify the reads using a database. Optional removal of non-MTBC reads will be built in.

**Comment by pmenzel** [comment]
To discuss that a bit:

I don't think that it is appropriate to include a read classification with kraken2 to the TB-profiler workflow.
TB-profiler as a standalone tool can just require the user to only input reads from MTB, and it's the responsibility of the user to do so, e.g. by preprocessing the reads before running TB-profiler.

Running kraken2 is a whole different scope in terms of storage and RAM requirements, compared with just running tb-profiler.
The database is very large and thre program also needs a lot of RAM.

Further, it is likely that true MTB reads are not annotated as MTB by kraken due to sequence homolgy with other mycobacteria, so one has to be careful how to select the reads to be excluded.

Maybe a workaround would be to use a strict filtering of the alignments from the bam file (or change settings in bwa-mem), so that only "good" alignments are retained and alignments from contaminating reads, which should have fewer matching bases, are excluded.

**Comment by jodyphelan** [comment]
Yes I think I agree with you here. I was thinking it would be nice to but I also ran into issues making it fit into the memory of a standard laptop. There are some genes like rpoB and rrs which are sometimes affected by contamination but after including filtering of soft-clipped reads with `samclip` in the v3 releases this has become less of an issue. I'll retire this from the roadmap for now.

Thanks for the input!

**Comment by jodyphelan** [comment]
Because clipped reads are used later in the pipeline by `delly`, a temporary bam file is created just for variant calling on which samclip is applied. Based on my tests samclip removes if either side or both are clipped. 

The coverage profile in the screenshot you provided is interesting. It looks like the proportion of contaminant sequences is a lot higher than Mtb sequences. 1.5m reads is more than enough if all the sequence was Mtb, but it could be that most of it is contamination. How does the coverage look for other parts of the genome (rpoB, katG etc..)?

**Comment by pmenzel** [comment]
They are two different samples in the screenshot.
The top one is contaminated with Streptococcus, and the high fraction of contaminant reads is probably due to higher copy number of the 16S gene in Streptococcus(?).

The bottom sample is clean, but has quite low coverage in rrs compared with other genes, the mean depth is 134x.

For comparison, here is the rpoB locus:
![grafik](https://user-images.githubusercontent.com/1469600/134361377-384d635d-c0a6-4b86-aec5-d63a460d569b.png)

Only a small part of the gene is also affected by the contaminant reads in the top sample.

btw, this is how kraken2 would see the top sample:
![grafik](https://user-images.githubusercontent.com/1469600/134362160-b3d4c440-3634-40e3-9579-a224e236328c.png)
