### ISSUE TITLE
tb-profiler collate KeyError: 'drugs'

### ISSUE THREAD

**Issue by lexleong** [jodyphelan/TBProfiler#163]
Hi Jody,

I have been running the tb-profiler collate on all my MTBs and have not been getting any issue. But today I got this issue (refer below) that I am not sure what is the reason. I wonder if you could quickly have a look to see what is the error and how do I fix it?

Cheers,
Lex

# tb-profiler error report

* OS: linux
* Program version: 3.0.4
* Database version: b2af444
* Program call:
```
{'prefix': '20210706', 'samples': None, 'dir': 'results', 'full': True, 'all_variants': True, 'mark_missing': False, 'reporting_af': 0.1, 'db': 'tbdb', 'external_db': None, 'func': <function main_collate at 0x7f13c45ef5e0>}
```
## Traceback:
```
  File "/home/users/iidlleo/miniconda3/bin/tb-profiler", line 571, in <module>
    args.func(args)
  File "/home/users/iidlleo/miniconda3/bin/tb-profiler", line 273, in main_collate
    tbp.collate_results(args.prefix,conf,sample_file=args.samples,result_dir=args.dir,reporting_af=args.reporting_af,mark_missing=args.mark_missing)
  File "/home/users/iidlleo/miniconda3/lib/python3.8/site-packages/tbprofiler/collate.py", line 58, in collate_results
    for d in x["drugs"]:
```
## Value:
```
'drugs'```

**Comment by jodyphelan** [comment]
Hi Lex,

It looks like this might be due to a format change in the output json file which happened between v2 and v3 of tb-profiler.

If you would like to include old runs you can try [this script](python ~/github/tbprofiler_scripts/tbprofiler_convert_to_v3.py 
) to convert the v2 json files to v3. If all your v2 json files are in a folder called "results" all you will need to do is run:
```python tbprofiler_convert_to_v3.py``` 

The converted files will be in a folder called results_v3 (you chan change the input and output folder names with `in-dir` and out-dir`. You can then add them to the rest of your v3 formatted output files. Alternatively, you can re-profile the raw data with the new version.

If you think this is not the issue then please let me know.

Jody

**Comment by lexleong** [comment]
Hi Jody,

Thank you so much for that! It worked after I removed the old output json files from my working /results folder! 

I will convert the tbprofiler_convert_to_v3.py soon.

Cheers,
Lex
