### ISSUE TITLE
sample fails processing with Pilon, works with other calling methods

### ISSUE THREAD

**Issue by jeffreybm** [jodyphelan/TBProfiler#210]
Hi Jody,

When processing a bioproject with 1200 samples using Pilon as the caller, all samples process fine except one.  This sample will go through TBprofiler succesfully when using freebayes or GATK as caller.  This is a public sample, SRA id SRR16087946.  I've attached the error log file to this issue.  

[SRR16087946.errlog.txt](https://github.com/jodyphelan/TBProfiler/files/8268720/SRR16087946.errlog.txt)

Chers,

Brendan

**Comment by jodyphelan** [comment]
Hi @jeffreybm ,

Interesting, I can't see the error from the log file but I will run the sample through myself and see if I can replicate the issue.

**Comment by jodyphelan** [comment]
It seems to be due to a line in the vcf output by pilon which bcftools doesn't like

```
Chromosome      767398  .       C       .       .       Del     DP=0;TD=44;BQ=0;MQ=60;QD=0;BC=0,0,0,0;QP=0,0,0,0;PC=114;IC=0;DC=44;XC=0;AC=2;AF=0.00    GT      1/1
```

The GT field indicates the alternate is present, but the alternate is set to '.'
This could be related to an indel found earlier on in the genome:
```
Chromosome      767371  .       CTGCGTCTGCTCGCCGTGGTGGATGAGC    CNNNNNNNNNNAAATGCCTGCGCGATGCGATTCTGCGTCTGCTCGCCGTGGTGGATGAG     .       PASS    SVTYPE=INS;SVLEN=31;END=767398;IMPRECISE        GT      1/1
```

I did find some other issues earlier with the vcf output format from pilon (https://github.com/broadinstitute/pilon/issues/141) which I had to manually change in tb-profiler. I could do something similar with this issue but ideally pilon should output a valid VCF file. Any thoughts?

**Comment by jeffreybm** [comment]
Hi @jodyphelan,

Thanks for looking in to this!  Ive had issues with the 'Del' FILTER flag in past too.  Our group will remove any entries with 'Del' FILTER flags, Pilon's description of this flag is that this entry is providing pileup information for a loci that is removed by variation in another line.  Like you mentioned above where position is covered by an indel elsewhere.  

However this doesn't address the main issue - why Pilon would use a non valid character in the ALT column.  I guess it's unclear if this '.' character in ALT column would only be found in those entries with 'Del' flag.  I agree though, Pilon should output a valid VCF line for all lines, regardless if line is expected to be filtered.

**Comment by jodyphelan** [comment]
This should now be fixed. I'll put out a new conda release soon too.
