### ISSUE TITLE
Unknown variant type

### ISSUE THREAD

**Issue by mbhall88** [jodyphelan/TBProfiler#249]
I have a TBProfiler (v4.3.0) run that failed with the last few lines of the log being

```
Running command:
set -u pipefail; samtools view -b -L /hps/nobackup/iqbal/mbhall/drprg/paper/.snakemake/conda/cf300545632060964f50d30e77483305_/share/tbprofiler//tbdb.barcode.bed /hps/nobackup/iqbal/mbhall/drprg/paper/results/depth/tbprofiler/5/nanopore/PRJNA650381/SAMN15703330/SRR12395162/2d303346-85d3-4176-bc7a-365ea0d79812.tmp.bam | bedtools coverage -a /hps/nobackup/iqbal/mbhall/drprg/paper/.snakemake/conda/cf300545632060964f50d30e77483305_/share/tbprofiler//tbdb.barcode.bed -b - -d -sorted
Unknown variant type ({'gene_name': 'fbiB', 'gene_id': 'Rv3262', 'feature_id': 'CCP46081', 'type': 'start_retained_variant', 'nucleotide_change': 'c.-2_1delGCTinsACC', 'protein_change': 'p.1?'}). Don't know how to rank... Exiting!
```

I am using a custom database, but I believe because these were in the watchlist tb-profiler still calls variants in them? I can remove this gene from the watchlist for now so I don't get the erorr, but though I would raise it in case there is a bug here.

**Comment by jodyphelan** [comment]
Thanks, I think it is ok to have the gene in the watchlist, the issue seems to be with the _start_retained_variant_ type. To select the main variant it uses the types to rank them from highest severity (e.g. transcript_ablation) to least (e.g. synonymous_variant). This list is hardcoded here: https://github.com/jodyphelan/pathogen-profiler/blob/master/pathogenprofiler/utils.py#L131. Not all variant types are present though and this seemed to have caused the error. I've put in a fix for this here https://github.com/jodyphelan/pathogen-profiler/commit/f336b16bd5a3186d7532c5c3940d595a69e5dd09. This will rank any variant not in the list as low. In the future it would be good to put every variant type into this ranking but this will require a bit more thought I think! I'm about to release a new version of TB-Profiler which should include this fix. Thanks for letting me know about it!
