### ISSUE TITLE
Accept VCF input

### ISSUE THREAD

**Issue by pvanheus** [jodyphelan/TBProfiler#33]
It would be good if TBProfiler could accept pre-computed VCF and then "profile" this VCF rather than re-calling variants. We already have a lot of VCF for our M. tuberculosis samples and re-running the analysis from BAM stage seems unnecessary.

**Comment by jodyphelan** [comment]
That is a good idea! I will take a look at including this in the release.

**Comment by jodyphelan** [comment]
@pvanheus This feature is now implemented. 

I would recommend only using this is if you believe the isolates have good coverage across the genome, as it will not be present to extract this from the VCF file. The main pipeline relies on extracting allelic depth from the FMT/AD tag in the VCF. If there is no AD tag present in the VCF file it sets the AD as "0,100", so it will not be possible to calculate frequency of mutation in the reads for these cases.

**Comment by malare** [comment]
First of all many thanks for this great tool. I would like to use it. However, I have the same issue as discussed here. How can I use tb-profiler with vcf files in the same way as bam/fastq files?

**Comment by jodyphelan** [comment]
Hi @malare,

This feature is already implemented using `tb-profiler vcf_profile <vcf_file>`. Let me know if there are any issues running this command.

Jody

**Comment by malare** [comment]
Hi @jodyphelan 
 thank you, do the vcf files have to have a certain format?
I got the message: 
set -u pipefail; bcftools index --threads 4 -f file.vcf.gz
index: "file.vcf.gz" is in a format that cannot be usefully indexed
Command Failed! Please Check!

**Comment by malare** [comment]
Hi @jodyphelan
thank you! Do the vcf files have to have a certain format?
I got the message:
set -u pipefail; bcftools index --threads 4 -f file.vcf
index: "file.vcf" is in a format that cannot be usefully indexed
Command Failed! Please Check!

my file looks like that:
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	GNubmber
Chromosome	1	.	T	.	.	PASS	ADP=16;WT=1;HET=0;HOM=0;NC=0	GT:GQ:SDP:DP:RD:AD:FREQ:PVAL:RBQ:ABQ:RDF:RDR:ADF:ADR	0/0:29:17:16:16:0:0%:1E0:40:0:8:8:0:0

........
Thank you

**Comment by jodyphelan** [comment]
Hi @malare ,

Format looks good, though your VCF file should be bgzipped. You can do this by doing `bcftools view file.vcf -Oz -o file.vcf.gz `

Jody

**Comment by malare** [comment]
Hi @jodyphelan 
Unfortunately, I have to write to you again. There is still a problem... Does this mean that the TB-Profiler-Pipline doesn't work with my vcfs? Is this because a different reference was used? Is there an option to include another reference?

tb-profiler vcf_profile file.vcf.gz

Running command:
set -u pipefail; bcftools index --threads 4 -f file.vcf.gz
Running command:
set -u pipefail; bcftools query -l file.vcf.gz > 938669.tmp.txt
Removing 938669.tmp.txt
Using gff file: /tbprofiler/tbdb.gff
Using ref file: /tbprofiler/tbdb.fasta
Using ann file: /tbprofiler/tbdb.ann.txt
Using barcode file: /tbprofiler/tbdb.barcode.bed
Using bed file: /tbprofiler/tbdb.bed
Using json_db file: /tbprofiler/tbdb.dr.json
Using version file: /tbprofiler/tbdb.version.json
Running command:
set -u pipefail; bcftools view -s file -c 1 -Oz -o 895988.tmp.txt file.vcf.gz
Running command:
set -u pipefail; bcftools view 895988.tmp.txt -h | grep "^##FORMAT=<ID=AD"
Running command:
set -u pipefail; bcftools view -a 895988.tmp.txt -Oz -o 165839.tmp.vcf.gz
Running command:
set -u pipefail; bcftools view -T /tbprofiler/tbdb.bed 165839.tmp.vcf.gz | bcftools csq -f /tbprofiler/tbdb.fasta -g /tbprofiler/tbdb.gff  -Oz -o 608567.tmp.vcf.gz -p a
Command Failed! Please Check!(tb_environment)

I am very grateful for any help, thank you!

**Comment by malare** [comment]
Hi @jodyphelan
Unfortunately, I have to write to you again. There is still a problem... Does this mean that the TB-Profiler-Pipline doesn't work with my vcf files? Is this because a different reference was used?

$ sed -i 's/MTB/Chromosome/g' "file.vcf"

$ bcftools view file.vcf -Oz -o file.vcf.gz
[W::vcf_parse] Contig 'Chromosome' is not defined in the header. (Quick workaround: index the file with tabix.)


$ tb-profiler vcf_profile file.vcf.gz

Running command:
set -u pipefail; bcftools index --threads 4 -f file.vcf.gz
Running command:
set -u pipefail; bcftools query -l file.vcf.gz > 938669.tmp.txt
Removing 938669.tmp.txt
Using gff file: /tbprofiler/tbdb.gff
Using ref file: /tbprofiler/tbdb.fasta
Using ann file: /tbprofiler/tbdb.ann.txt
Using barcode file: /tbprofiler/tbdb.barcode.bed
Using bed file: /tbprofiler/tbdb.bed
Using json_db file: /tbprofiler/tbdb.dr.json
Using version file: /tbprofiler/tbdb.version.json
Running command:
set -u pipefail; bcftools view -s file -c 1 -Oz -o 895988.tmp.txt file.vcf.gz
Running command:
set -u pipefail; bcftools view 895988.tmp.txt -h | grep "^##FORMAT=<ID=AD"
Running command:
set -u pipefail; bcftools view -a 895988.tmp.txt -Oz -o 165839.tmp.vcf.gz
Running command:
set -u pipefail; bcftools view -T /tbprofiler/tbdb.bed 165839.tmp.vcf.gz | bcftools csq -f /tbprofiler/tbdb.fasta -g /tbprofiler/tbdb.gff -Oz -o 608567.tmp.vcf.gz -p a
Command Failed! Please Check!(tb_environment)


I am very grateful for any help, thank you!

**Comment by jodyphelan** [comment]
Can you run 

```bcftools view -T /tbprofiler/tbdb.bed 165839.tmp.vcf.gz | bcftools csq -f /tbprofiler/tbdb.fasta -g /tbprofiler/tbdb.gff -Oz -o 608567.tmp.vcf.gz -p a```

 and send the output?

**Comment by malare** [comment]
Thank you for your help. Following you can see the output:

Parsing /tbprofiler/tbdb.gff ...
Indexed 4034 transcripts, 4035 exons, 4018 CDSs, 0 UTRs
Ignored the following biotypes:
        60x     .. ncRNA
        90x     .. tRNA
Calling...
Error: the fasta reference does not match the VCF REF allele at Chromosome:9143 .. C

So, there is an issue with the reference used? Do you know if it can be fixed?
Thank you :)

**Comment by jodyphelan** [comment]
Yes it is probably because you have used a different reference than the database is based on. At the moment there is no quick fix. You would have to either lift over the coordinates from one reference to the other although that would not guarantee that the nucleotide are the same on equivalent positions. The best way is to use tb-profiler on the raw fastq data is you still have access.

Jody

**Comment by malare** [comment]
Unfortunately, I don't have access to the raw sequences at the moment (I have only vcf files).. What do you mean with "You would have to either lift over the coordinates from one reference to the other although that would not guarantee that the nucleotide are the same on equivalent positions." 
Is it not possible to exchange the tbdb.fasta and other files with the used reference?
Thank you

**Comment by jodyphelan** [comment]
Different references will have different sizes (because of indels), so the genomic positions for genes/sites will be different for the references. The annotation by bcftools checks to see if the reference allele in the VCF agrees with the fasta file of the reference. In your case it looks, like the nucleotide at position 9143 is different between the files due to the different references used. You would have to build the database for your specific reference. You can find an example of how to do this [here](https://github.com/jodyphelan/tbdb_NC_018143.2) if you are interested.

**Comment by malare** [comment]
Okay, thanks. 
However, I'm not sure which files I have to use in the following:
minimap2 genome.fasta ~/refgenome/MTB-h37rv_asm19595v2-eg18.fa --cs -cL > aln.paf

genome.fasta: Would that be my reference genome?
and what should this be:
~/refgenome/MTB-h37rv_asm19595v2-eg18.fa

Both files seem to contain the same sequence data.


And if everything will work, I have to use:
tb-profiler vcf_profile file.vcf
with or without: --db DB_Name -t 4  --txt
?

thank you:)

**Comment by malare** [comment]
Okay, thanks.
However, I'm not sure which files I have to use in the following:
minimap2 genome.fasta ~/refgenome/MTB-h37rv_asm19595v2-eg18.fa --cs -cL > aln.paf
genome.fasta: Would that be my reference genome?
and how can I get this/should I include my reference?
~/refgenome/MTB-h37rv_asm19595v2-eg18.fa

And if everything will work, I have to use:
tb-profiler vcf_profile file.vcf
with or without: --db DB_Name -t 4 --txt
?

thank you:)
