### ISSUE TITLE
delly shared libraries issue

### ISSUE THREAD

**Issue by flashton2003** [jodyphelan/TBProfiler#88]
Hi Jody,

I'm having a problem with delly as part of the tb-profiler workflow.

I'm working on an ubuntu 16.04 instance, fresh conda env install with the below defining yaml.

```name: tb_profiler_v2.8.5
channels:
- defaults
- bioconda
- conda-forge
dependencies:
- tb-profiler
```
Below is the output of `conda list`

```
# packages in environment at /home/ubuntu/anaconda3/envs/tb_profiler_v2.8.5:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
bcftools                  1.9                  ha228f0b_4    bioconda
bedtools                  2.29.2               hc088bd4_0    bioconda
biopython                 1.74             py37h7b6447c_0  
blas                      1.0                         mkl  
bowtie2                   2.3.5.1          py37he513fc3_0    bioconda
bwa                       0.7.17               hed695b0_7    bioconda
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.1.1                      0  
certifi                   2019.11.28               py37_0  
curl                      7.68.0               hbc83047_0  
delly                     0.8.1                h4037b6b_2    bioconda
expat                     2.2.6                he6710b0_0  
gatk4                     4.1.4.1                       1    bioconda
git                       2.23.0          pl526hacde149_0  
htslib                    1.9                  ha228f0b_7    bioconda
icu                       58.2                 h9c2bf20_1  
intel-openmp              2020.0                      166  
krb5                      1.17.1               h173b8e3_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libboost                  1.71.0               h97c9712_0  
libcurl                   7.68.0               h20c2e04_0  
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libssh2                   1.8.2                h1ba5d50_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
minimap2                  2.17                 h8b12597_1    bioconda
mkl                       2020.0                      166  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.0.15           py37ha843d7b_0  
mkl_random                1.1.0            py37hd6b4f25_0  
ncurses                   6.1                  he6710b0_1  
numpy                     1.18.1           py37h4f9e942_0  
numpy-base                1.18.1           py37hde5b4d6_1  
openjdk                   8.0.152              h7b6447c_2  
openssl                   1.1.1d               h7b6447c_4  
parallel                  20160622                      1    bioconda
pcre                      8.43                 he6710b0_0  
perl                      5.26.2               h14c3975_0  
perl-threaded             5.26.0                        0    bioconda
pip                       20.0.2                   py37_1  
python                    3.7.6                h0371630_2  
readline                  7.0                  h7b6447c_5  
samtools                  1.9                 h10a08f8_12    bioconda
setuptools                45.2.0                   py37_0  
six                       1.14.0                   py37_0  
sqlite                    3.31.1               h7b6447c_0  
tb-profiler               2.8.5                      py_0    bioconda
tbb                       2020.0               hfd86e86_0  
tk                        8.6.8                hbc83047_0  
tqdm                      4.42.1                     py_0  
trimmomatic               0.39                          1    bioconda
wheel                     0.34.2                   py37_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0 
```

And here is the output of the failing delly command.

```$ delly call -t DEL -g /home/ubuntu/anaconda3/envs/tb_profiler_v2.8.5/share/tbprofiler/tbdb.fasta ./14742-WTCHG_689876_70145086.full_profile.bam -o ./14742-WTCHG_689876_70145086.full_profile.delly.bcf
delly: error while loading shared libraries: libboost_iostreams.so.1.67.0: cannot open shared object file: No such file or directory
```

I solved the issue by running `conda update delly`. Just an FYI in case this is something you can fix in the conda recipe?

**Comment by jodyphelan** [comment]
Hey @flashton2003 thanks for the heads up! Not sure what caused the issue but I'll try force the latest version of delly in the conda recipe and hopefully that should solve the issue.

Jody

**Comment by flashton2003** [comment]
Thanks!

**Comment by eidamama** [comment]
Hi, I had the same issue when try to run delly on  ubuntu 16.04. I run conda update delly too, still, the "error while loading shared libraries: libboost_iostreams.so.1.67.0: cannot open shared object file: No such file or directory" remains. Anyone has more solution?

**Comment by jodyphelan** [comment]
Does it work if you try to create a new environment with `conda create -n tb-profiler tb-profiler=2.8.13`?

**Comment by eidamama** [comment]
> Hi @eidamama
> 
> Does it work if you try to create a new environment with `conda create -n tb-profiler tb-profiler=2.8.13`?

Hi Jody
   I tried your method and the issue solved after auto-downloading several modules. Now delly runs well. Thank you so mcuh.

**Comment by jodyphelan** [comment]
Great news!

**Comment by biomedswe** [comment]
Hi! I'm totally new to this so I hope it's ok if I write here even if this is closed?


I work on Ubuntu 20.04.1 LTS and have created a new environment:
conda create --name sequencing -c bioconda bwa picard gatk4 delly manta bcftools

When I try to run delly, I get this same problem: 
delly: error while loading shared libraries: libboost_iostreams.so.1.67.0: cannot open shared object file: No such file or directory

conda list output:

![image](https://user-images.githubusercontent.com/64096349/107259279-1a328580-6a3d-11eb-95e2-c7040e814040.png)
![image](https://user-images.githubusercontent.com/64096349/107259370-320a0980-6a3d-11eb-8ff5-0d00d19dc9e1.png)

How can I solve this?

**Comment by flashton2003** [comment]
Did you run `conda update delly`?

**Comment by biomedswe** [comment]
yes, I only get this:

![image](https://user-images.githubusercontent.com/64096349/107265600-c2981800-6a44-11eb-819f-5cd672cc92c6.png)

![image](https://user-images.githubusercontent.com/64096349/107265661-d17eca80-6a44-11eb-9924-d7ef555cf093.png)

**Comment by jodyphelan** [comment]
Does it update if you run  ```conda install delly=0.8.7```

**Comment by jodyphelan** [comment]
> Hi @eidamama
> 
> Does it work if you try to create a new environment with `conda create -n tb-profiler tb-profiler=2.8.13`?

You could try this again? Sometimes installing software with many dependancies into an existing environment can cause some conflicts and conda doesn't always get the libraries right.

**Comment by biomedswe** [comment]
> Does it update if you run `conda install delly=0.8.7`?

no it doesn't work:

![image](https://user-images.githubusercontent.com/64096349/107389538-2713af80-6af7-11eb-8ea4-5cbeb24f3a28.png)

I also tried to write: conda create --name sequencing -c bioconda bwa picard gatk4 delly=0.8.7 manta bcftools directly when I created the environment but it found conflict there as well.

The only way I have found it to work is if I download delly 0.8.7 from their github and replace the faulty delly file with this one, then all works fine. Only I hoped that conda would make things simpler to install:(

**Comment by jodyphelan** [comment]
I have tested this command on Ubuntu 20.04 LTS and it seems to work: ```conda create -n tb-profiler tb-profiler=2.8.14 python=3.7 ```. I am not quite sure why conda can't seem to figure out how to install all the deps correctly but given that your OS is the same build I think this should work. One thing to note is when creating a new environment that you only install packages you actually need to run tb-profiler. I can see you are also installing manta which isn't used by the pipeline and relies on python2.7. As of Jan 2020 it is no longer supported and could lead to problems with other packages, so I would recommend installing into a different env if you need to run it. 

I also have attached an explicit list which you can use to build and identical environment to mine: [spec-file.txt](https://github.com/jodyphelan/TBProfiler/files/5952762/spec-file.txt). You should be able to create and env with ```conda create --name myenv --file spec-file.txt```

Hope this helps with your installation options!

Jody

**Comment by biomedswe** [comment]
Oh I'm sorry, I'm not using the tb-profiler pipeline so I maybe shouldn't have written in this thread. I'm trying to run GDC dna-seq  pipeline, maybe I should start another thread for that? sorry for this misstake!

cause the exact tools i need for this pipeline is: bwa picard gatk4 delly manta bcftools (and also samtools which I missed to write first)

best/jonas

**Comment by jodyphelan** [comment]
Ahh right, no problem... you could try post in the https://github.com/bioconda/bioconda-recipes repo maybe?

**Comment by GENEDECODERS** [comment]
> 

Hi, Jody
I followed your instructions and used your spec-file.txt, The problem is still here.
(base) jiaxue@jiaxue32:~$ delly call -t DEL -g /home/jiaxue/Downloads/data/resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta  -o /home/jiaxue/Downloads/data/RR25119mem-pe.bcf /home/jiaxue/Downloads/data/ERR25119mem-pe.final.bam
delly: error while loading shared libraries: libboost_iostreams.so.1.67.0: cannot open shared object file: No such file or directory
(base) jiaxue@jiaxue32:~$ conda create --name myenv --file /home/jiaxue/Downloads/spec-file.txt

Downloading and Extracting Packages
ca-certificates-2020 | ############################################################################################################################################################################ | 100% 
ld_impl_linux-64-2.3 | ############################################################################################################################################################################ | 100% 
libgfortran5-9.3.0   | ############################################################################################################################################################################ | 100% 
libstdcxx-ng-9.3.0   | ############################################################################################################################################################################ | 100% 
openjdk-8.0.265      | ############################################################################################################################################################################ | 100% 
libgfortran-ng-9.3.0 | ############################################################################################################################################################################ | 100% 
libgomp-9.3.0        | ############################################################################################################################################################################ | 100% 
_openmp_mutex-4.5    | ############################################################################################################################################################################ | 100% 
libgcc-ng-9.3.0      | ############################################################################################################################################################################ | 100% 
c-ares-1.17.1        | ############################################################################################################################################################################ | 100% 
expat-2.2.10         | ############################################################################################################################################################################ | 100% 
icu-67.1             | ############################################################################################################################################################################ | 100% 
libdeflate-1.6       | ############################################################################################################################################################################ | 100% 
libev-4.33           | ############################################################################################################################################################################ | 100% 
libffi-3.3           | ############################################################################################################################################################################ | 100% 
libopenblas-0.3.12   | ############################################################################################################################################################################ | 100% 
lz4-c-1.9.3          | ############################################################################################################################################################################ | 100% 
ncurses-6.2          | ############################################################################################################################################################################ | 100% 
openssl-1.1.1i       | ############################################################################################################################################################################ | 100% 
pcre-8.44            | ############################################################################################################################################################################ | 100% 
perl-5.32.0          | ############################################################################################################################################################################ | 100% 
tbb-2020.2           | ############################################################################################################################################################################ | 100% 
zlib-1.2.11          | ############################################################################################################################################################################ | 100% 
bedtools-2.30.0      | ############################################################################################################################################################################ | 100% 
bwa-0.7.17           | ############################################################################################################################################################################ | 100% 
gettext-0.19.8.1     | ############################################################################################################################################################################ | 100% 
k8-0.2.5             | ############################################################################################################################################################################ | 100% 
libblas-3.9.0        | ############################################################################################################################################################################ | 100% 
libnghttp2-1.43.0    | ############################################################################################################################################################################ | 100% 
libssh2-1.9.0        | ############################################################################################################################################################################ | 100% 
parallel-20201122    | ############################################################################################################################################################################ | 100% 
readline-8.0         | ############################################################################################################################################################################ | 100% 
tk-8.6.10            | ############################################################################################################################################################################ | 100% 
zstd-1.4.8           | ############################################################################################################################################################################ | 100% 
boost-cpp-1.70.0     | ############################################################################################################################################################################ | 100% 
krb5-1.17.2          | ############################################################################################################################################################################ | 100% 
libcblas-3.9.0       | ############################################################################################################################################################################ | 100% 
liblapack-3.9.0      | ############################################################################################################################################################################ | 100% 
minimap2-2.17        | ############################################################################################################################################################################ | 100% 
sqlite-3.34.0        | ############################################################################################################################################################################ | 100% 
libcurl-7.71.1       | ############################################################################################################################################################################ | 100% 
python-3.7.9         | ############################################################################################################################################################################ | 100% 
curl-7.71.1          | ############################################################################################################################################################################ | 100% 
gatk4-4.1.9.0        | ############################################################################################################################################################################ | 100% 
htslib-1.10.2        | ############################################################################################################################################################################ | 100% 
python_abi-3.7       | ############################################################################################################################################################################ | 100% 
tqdm-4.56.0          | ############################################################################################################################################################################ | 100% 
trimmomatic-0.39     | ############################################################################################################################################################################ | 100% 
wheel-0.36.2         | ############################################################################################################################################################################ | 100% 
bcftools-1.10.2      | ############################################################################################################################################################################ | 100% 
bowtie2-2.4.2        | ############################################################################################################################################################################ | 100% 
certifi-2020.12.5    | ############################################################################################################################################################################ | 100% 
delly-0.8.7          | ############################################################################################################################################################################ | 100% 
git-2.30.0           | ############################################################################################################################################################################ | 100% 
numpy-1.20.0         | ############################################################################################################################################################################ | 100% 
samtools-1.10        | ############################################################################################################################################################################ | 100% 
biopython-1.78       | ############################################################################################################################################################################ | 100% 
setuptools-49.6.0    | ############################################################################################################################################################################ | 100% 
pip-21.0.1           | ############################################################################################################################################################################ | 100% 
tb-profiler-2.8.14   | ############################################################################################################################################################################ | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(base) jiaxue@jiaxue32:~$ delly call -t DEL -g /home/jiaxue/Downloads/data/resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta  -o /home/jiaxue/Downloads/data/RR25119mem-pe.bcf /home/jiaxue/Downloads/data/ERR25119mem-pe.final.bam
delly: error while loading shared libraries: libboost_iostreams.so.1.67.0: cannot open shared object file: No such file or directory

**Comment by GENEDECODERS** [comment]
delly: error while loading shared libraries: libboost_iostreams.so.1.67.0: cannot open shared object file: No such file or directory
(base) jiaxue@jiaxue32:~$ conda create -n tb-profiler tb-profiler=2.8.14 python=3.7 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - tb-profiler=2.8.14

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by jodyphelan** [comment]
Hi @GENEDECODERS ,

It looks like you haven't added the bioconda channel. You can do this by running

```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```

Then after you should be able to install. Btw I see you are insalling v2.8.14... just to let you know that there are newer versions available.

```
conda create -n tb-profiler tb-profiler=4.1.1
```
