### ISSUE TITLE
Replacement (or plugin option) for delly

### ISSUE THREAD

**Issue by tseemann** [jodyphelan/TBProfiler#95]
I notice delly is used.
I think it is to check for deletion of some genes (penA?)

Was wondering if you could just use `bedtools coverage -a out.bam -b tbdb.bed` or similar with `samtools depth -aa` to check if zero or low depth in that region of the genome?

**Comment by jodyphelan** [comment]
Yeah I do have a bedrooms cov step in there to check the proportion of the genes covered by at least one base (only store in the json atm). I've noticed that in some isolates coverage drops to zero due to poor sequencing or data preprocessing rather than an actual deletion so I've used Delly to properly check using split read support.

**Comment by jodyphelan** [comment]
I could add in a `--no_delly` option if it is overkill for some use cases.

**Comment by tseemann** [comment]
I was just thinking you could have a `--deletion_caller` module like you have for `--aligner` etc
With options `delly` `bedtools` etc

**Comment by jodyphelan** [comment]
Oh yeah I could do that... Ok I'll try put something together over the next week

**Comment by jodyphelan** [comment]
Sorry, took me a while to get to this! I've now added in some functionality to extract the fraction of a gene which falls below a user-defined cutoff (0 by default). At the moment I just report the number and let the user decide themselves if it is a deletion or just low coverage as it might be a bit tricky to find one rule which fits all.

**Comment by tseemann** [comment]
Thanks @jodyphelan !
